name: Internship CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas

    # Setup Node.js (for Newman)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman & Reporter
      run: |
        npm install -g newman newman-reporter-htmlextra

    # Run Selenium Tests
    - name: Run Selenium Data Driven Tests
      run: |
        python selenium_ddt_csv.py || true

    # Run API Tests
    - name: Run Newman API Tests
      run: |
        newman run task2_api_testing/API_Testing_Collection.postman_collection.json -r htmlextra --reporter-htmlextra-export api_test_report.html

    # Upload Reports
    - name: Upload API Report
      uses: actions/upload-artifact@v3
      with:
        name: api-test-report
        path: api_test_report.html
